# Configuration File Of ItemInteract 
# aurthor MrNinja008
#  _____ _                  _____      _                      _   
# |_   _|                  |_   _|    | |                    | |  
#   | | |_ ___ _ __ ___      | | _ __ | |_ ___ _ __ __ _  ___| |_ 
#   | | __/ _ \ '_ ` _ \     | || '_ \| __/ _ \ '__/ _` |/ __| __|
#  _| |_| ||  __/ | | | | | _| || | | | ||  __/ | | (_| | (__| |_ 
#  \___/ \__\___|_| |_| |_| \___/_| |_|\__\___|_|  \__,_|\___|\__|
#DisplayName Aka Custom Name for the item 
DisplayName: "ItemInteract"
#
# Minecraft Item ID NOTE Dont Not Use ItemID if that item not implemented by Pocketmine
ItemID: "1:0:1" #format ID:META:COUNT
#
#HotBarSlot 1 to 9
HotBarSlot: "1"
#
# Command That you whant To Execute While You Click With that item
command: "help" 
#item Lore! Can be custom
Lore: "ItemInteract"
# NOTE Do not Put "/" in config
